-- liquibase formatted sql

-- changeset nagp:CREATE_TABLE_quotes
CREATE TABLE "quotes" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "quote" VARCHAR(250) NOT NULL, "author" VARCHAR(100));
-- changeset nagp:POPULATE_TABLE_quotes
INSERT INTO quotes (quote, author) VALUES
( 'Be the change that you wish to see in the world.', 'Mahatma Gandhi'),
('In the middle of every difficulty lies opportunity.','Albert Einstein'),
('Do not go where the path may lead, go instead where there is no path and leave a trail.','Ralph Waldo Emerson'),
('Success is not final, failure is not fatal: It is the courage to continue that counts.','Winston Churchill'),
('Whether you think you can, or you think you can’t — you’re right.','Henry Ford'),
('The only limit to our realization of tomorrow is our doubts of today.','Franklin D. Roosevelt'),
('Your time is limited, so don’t waste it living someone else’s life.','Steve Jobs'),
('It always seems impossible until it’s done.','Nelson Mandela'),
('You miss 100% of the shots you don’t take.','Wayne Gretzky'),
('What you get by achieving your goals is not as important as what you become by achieving your goals.','Zig Ziglar')
