apiVersion: apps/v1
kind: Deployment
metadata:
  name: quotes-service-deployment
  labels:
    app: quotes-service
spec:
  replicas: 4
  selector:
    matchLabels:
      app: quotes-service
  template:
    metadata:
      labels:
        app: quotes-service
    spec:
      containers:
        - name:  quotes-service
          image: {DOCKER_IMAGE}
          imagePullPolicy: Always
          env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: nagp-db-config
                  key: db_url

            - name: DB_DRIVER
              valueFrom:
                configMapKeyRef:
                  name: nagp-db-config
                  key: db_driver

            - name: HIBERNATE_DIALECT
              valueFrom:
                configMapKeyRef:
                  name: nagp-db-config
                  key: hibernate_dialect

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: nagp-db-secret
                  key: db_username

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nagp-db-secret
                  key: db_password
          ports:
            - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: quotes-service
spec:
  selector:
    app: quotes-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
