spring:
  application:
    name: quotes-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: ${HIBERNATE_DIALECT}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  management:
    server:
      port: 8080
    endpoint:
      health:
        show-details: always
        probes:
          enabled: true
        group:
          liveness:
            include: livenessState
          readiness:
            include: readinessState
    endpoints:
      web:
        exposure:
          include: '*'
    health:
      livenessState:
        enabled: true
      readinessState:
        enabled: true
